In [1]:
import pandas as pd

## Vivienda

In [29]:
file = "../../dataframes/enh/enh_transf_2016.csv"

In [30]:
df = pd.read_csv(filepath_or_buffer=file)

In [31]:
df.shape

(50643, 63)

In [32]:
df.isnull().any().any()

False

In [33]:
df.columns

Index(['Unnamed: 0', 'tipo_viv', 'mat_pared', 'mat_techos', 'mat_pisos',
       'ais_techos', 'ais_pared', 'ais_ventan', 'ais_otro', 'cocina_dor',
       'disp_agua', 'dotac_agua', 'uso_compar', 'sanit_agua', 'drenaje',
       'disp_elect', 'combustible', 'eli_basura', 'lavadero', 'fregadero',
       'regadera', 'rega_elect', 'tinaco_azo', 'cisterna', 'pileta',
       'calent_sol', 'calent_gas', 'medidor_luz', 'bomba_agua', 'tanque_gas',
       'aire_acond', 'calefacc', 'chimenea', 'repar_pard', 'repar_tech',
       'repar_agua', 'repar_dren', 'repar_cabl', 'const_dorm', 'const_coci',
       'const_bano', 'const_neg', 'tenencia', 'computador', 'tel_fijo',
       'celular', 'internet', 'tv_paga', 'auto_pick', 'ent', 'mun', 'loc',
       'cuart_dorm', 'num_cuarto', 'bano_comp', 'bano_excus', 'bano_regad',
       'focos_inca', 'focos_ahor', 'tot_resid', 'tot_hog', 'tam_loc',
       'est_socio'],
      dtype='object')

In [34]:
df.drop(labels='Unnamed: 0', axis=1, inplace=True)

In [35]:
df[(df.ent == 9)]

,tipo_viv,mat_pared,mat_techos,mat_pisos,ais_techos,ais_pared,ais_ventan,ais_otro,cocina_dor,disp_agua,...,num_cuarto,bano_comp,bano_excus,bano_regad,focos_inca,focos_ahor,tot_resid,tot_hog,tam_loc,est_socio
12700,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,0,0,0,10,4,1,1,3
12701,0.037142,0.904291,0.790001,0.525107,0.008037,0.007089,0.005786,0.005647,0.932765,0.807476,...,4,2,0,0,0,10,3,1,1,3
12702,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,2,0,0,15,0,3,1,1,3
12703,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,0,0,0,17,4,1,1,3
12704,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,2,1,0,0,0,2,1,1,1,3
12705,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,1,0,1,0,2,0,1,1,1,2
12706,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,2,0,1,1,1,2
12707,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,0,0,0,6,3,1,1,2
12708,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,6,3,1,1,2
12709,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,2,1,0,0,0,2,1,1,1,2
12710,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,2,0,0,0,11,4,1,1,2
12711,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,1,0,0,10,1,1,1,2
12712,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,6,5,1,1,2
12713,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,11,1,1,1,3
12714,0.954999,0.904291,0.045258,0.461584,0.942184,0.981162,0.986454,0.992457,0.067235,0.192524,...,1,0,1,0,0,2,3,1,1,3
12715,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,7,2,0,0,10,4,3,1,1,3
12716,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,10,3,1,1,3
12717,0.954999,0.904291,0.045258,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,6,0,3,1,1,3
12718,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,0,0,0,7,3,1,1,3
12719,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,0,0,0,6,4,1,1,3
12720,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,0,0,2,4,3,1,1,3
12721,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,0,0,0,6,1,1,1,3
12722,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,6,1,0,0,0,9,11,3,1,3
12723,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,7,2,0,0,0,13,9,1,1,3
12724,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,6,1,1,0,5,2,6,1,1,3
12725,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,1,0,6,3,5,1,1,3
12726,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,6,4,1,1,3
12727,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,0,0,6,0,6,1,1,3
12728,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,0,0,2,2,5,1,1,3
12729,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,10,3,1,0,0,40,4,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14413,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,0,0,0,10,5,1,1,3
14414,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,5,3,1,1,3
14415,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,0,0,0,8,5,1,1,3
14416,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,0,0,0,5,3,1,1,3
14417,0.037142,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,4,2,1,1,3
14418,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,5,1,0,0,0,13,3,1,1,4
14419,0.037142,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,2,1,0,0,3,8,2,1,1,4
14420,0.037142,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,1,0,0,8,1,1,1,4
14421,0.037142,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,2,1,0,0,0,4,3,1,1,4
14422,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,4,1,0,0,0,5,5,1,4,2
14423,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,5,0,1,0,3,5,7,1,4,2
14424,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.067235,0.807476,...,2,0,1,0,0,2,8,1,4,2
14425,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,2,6,4,1,4,2
14426,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,3,0,5,1,4,2
14427,0.954999,0.904291,0.005529,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,3,0,1,0,3,2,7,1,4,2
14428,0.954999,0.904291,0.109512,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,5,0,1,0,5,0,8,1,4,2
14429,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,4,0,1,0,0,5,6,1,4,2
14430,0.954999,0.904291,0.005529,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,0,2,0,0,5,3,1,4,2
14431,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,4,1,3,1,4,2
14432,0.954999,0.904291,0.790001,0.525107,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,3,1,0,0,0,7,3,1,4,2
14433,0.954999,0.904291,0.045258,0.461584,0.942184,0.981162,0.986454,0.992457,0.067235,0.192524,...,1,0,1,0,0,3,3,1,4,2
14434,0.954999,0.904291,0.045258,0.013309,0.942184,0.981162,0.986454,0.992457,0.067235,0.192524,...,1,0,1,0,0,1,5,1,4,2
14435,0.954999,0.904291,0.045258,0.461584,0.942184,0.981162,0.986454,0.992457,0.067235,0.192524,...,1,0,1,0,1,0,1,1,4,2
14436,0.954999,0.904291,0.109512,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.807476,...,2,0,1,0,2,0,5,1,4,2
14437,0.954999,0.904291,0.045258,0.461584,0.942184,0.981162,0.986454,0.992457,0.067235,0.192524,...,1,1,0,0,0,3,3,1,4,2
14438,0.954999,0.904291,0.012025,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,0,5,2,1,4,2
14439,0.954999,0.904291,0.109512,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,2,5,4,1,4,2
14440,0.954999,0.904291,0.045258,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,2,2,3,1,4,2
14441,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,0,5,3,1,4,2
14442,0.954999,0.904291,0.790001,0.461584,0.942184,0.981162,0.986454,0.992457,0.932765,0.192524,...,2,0,1,0,0,2,1,1,4,2

In [36]:
df_cdmx = df[(df.ent == 9)]

In [37]:
for column in df_cdmx.columns:
    print(column)
    print('nunique', ':', df_cdmx[column].nunique())
    print('value counts', ':', df_cdmx[column].value_counts())
    print('_________________________________________________')

tipo_viv
nunique : 4
value counts : 0.954999    1173
0.037142     547
0.007444      17
0.000336       6
Name: tipo_viv, dtype: int64
_________________________________________________
mat_pared
nunique : 5
value counts : 0.904291    1730
0.060541       8
0.025433       3
0.000553       1
0.002745       1
Name: mat_pared, dtype: int64
_________________________________________________
mat_techos
nunique : 6
value counts : 0.790001    1638
0.045258      62
0.109512      30
0.005529       8
0.024051       3
0.012025       2
Name: mat_techos, dtype: int64
_________________________________________________
mat_pisos
nunique : 3
value counts : 0.525107    1159
0.461584     578
0.013309       6
Name: mat_pisos, dtype: int64
_________________________________________________
ais_techos
nunique : 3
value counts : 0.942184    1685
0.049780      38
0.008037      20
Name: ais_techos, dtype: int64
_________________________________________________
ais_pared
nunique : 3
value counts : 0.981162    1707
0.007089      21
0.011749      15
Name: ais_pared, dtype: int64
_________________________________________________
ais_ventan
nunique : 3
value counts : 0.986454    1705
0.005786      21
0.007760      17
Name: ais_ventan, dtype: int64
_________________________________________________
ais_otro
nunique : 3
value counts : 0.992457    1722
0.005647      20
0.001896       1
Name: ais_otro, dtype: int64
_________________________________________________
cocina_dor
nunique : 2
value counts : 0.932765    1623
0.067235     120
Name: cocina_dor, dtype: int64
_________________________________________________
disp_agua
nunique : 2
value counts : 0.807476    1536
0.192524     207
Name: disp_agua, dtype: int64
_________________________________________________
dotac_agua
nunique : 5
value counts : 0.746125    1398
0.146911     167
0.046028      82
0.034378      70
0.026558      26
Name: dotac_agua, dtype: int64
_________________________________________________
uso_compar
nunique : 2
value counts : 0.960429    1620
0.039571     123
Name: uso_compar, dtype: int64
_________________________________________________
sanit_agua
nunique : 3
value counts : 0.762909    1507
0.200877     234
0.036214       2
Name: sanit_agua, dtype: int64
_________________________________________________
drenaje
nunique : 4
value counts : 0.779081    1650
0.185633      84
0.005865       8
0.027329       1
Name: drenaje, dtype: int64
_________________________________________________
disp_elect
nunique : 2
value counts : 0.998223    1742
0.000652       1
Name: disp_elect, dtype: int64
_________________________________________________
combustible
nunique : 5
value counts : 0.820864    1425
0.058587     289
0.012440      26
0.002863       2
0.102838       1
Name: combustible, dtype: int64
_________________________________________________
eli_basura
nunique : 5
value counts : 0.833936    1545
0.066781     188
0.010939       8
0.082381       1
0.003910       1
Name: eli_basura, dtype: int64
_________________________________________________
lavadero
nunique : 2
value counts : 0.852043    1631
0.147957     112
Name: lavadero, dtype: int64
_________________________________________________
fregadero
nunique : 2
value counts : 0.668997    1348
0.331003     395
Name: fregadero, dtype: int64
_________________________________________________
regadera
nunique : 2
value counts : 0.785696    1521
0.214304     222
Name: regadera, dtype: int64
_________________________________________________
rega_elect
nunique : 2
value counts : 0.963233    1728
0.036767      15
Name: rega_elect, dtype: int64
_________________________________________________
tinaco_azo
nunique : 2
value counts : 0.607093    1381
0.392907     362
Name: tinaco_azo, dtype: int64
_________________________________________________
cisterna
nunique : 2
value counts : 0.209703    1057
0.790297     686
Name: cisterna, dtype: int64
_________________________________________________
pileta
nunique : 2
value counts : 0.411113    1112
0.588887     631
Name: pileta, dtype: int64
_________________________________________________
calent_sol
nunique : 2
value counts : 0.948226    1696
0.051774      47
Name: calent_sol, dtype: int64
_________________________________________________
calent_gas
nunique : 2
value counts : 0.45953    1430
0.54047     313
Name: calent_gas, dtype: int64
_________________________________________________
medidor_luz
nunique : 2
value counts : 0.956697    1676
0.043303      67
Name: medidor_luz, dtype: int64
_________________________________________________
bomba_agua
nunique : 2
value counts : 0.24181    1107
0.75819     636
Name: bomba_agua, dtype: int64
_________________________________________________
tanque_gas
nunique : 2
value counts : 0.890883    1201
0.109117     542
Name: tanque_gas, dtype: int64
_________________________________________________
aire_acond
nunique : 2
value counts : 0.786091    1734
0.213909       9
Name: aire_acond, dtype: int64
_________________________________________________
calefacc
nunique : 2
value counts : 0.974587    1733
0.025413      10
Name: calefacc, dtype: int64
_________________________________________________
chimenea
nunique : 2
value counts : 0.967458    1715
0.032542      28
Name: chimenea, dtype: int64
_________________________________________________
repar_pard
nunique : 2
value counts : 0.54975    1070
0.45025     673
Name: repar_pard, dtype: int64
_________________________________________________
repar_tech
nunique : 2
value counts : 0.546808    1232
0.453192     511
Name: repar_tech, dtype: int64
_________________________________________________
repar_agua
nunique : 2
value counts : 0.818415    1508
0.181585     235
Name: repar_agua, dtype: int64
_________________________________________________
repar_dren
nunique : 2
value counts : 0.871907    1564
0.128093     179
Name: repar_dren, dtype: int64
_________________________________________________
repar_cabl
nunique : 2
value counts : 0.800111    1485
0.199889     258
Name: repar_cabl, dtype: int64
_________________________________________________
const_dorm
nunique : 2
value counts : 0.587603    1260
0.412397     483
Name: const_dorm, dtype: int64
_________________________________________________
const_coci
nunique : 2
value counts : 0.743755    1487
0.256245     256
Name: const_coci, dtype: int64
_________________________________________________
const_bano
nunique : 2
value counts : 0.672354    1425
0.327646     318
Name: const_bano, dtype: int64
_________________________________________________
const_neg
nunique : 2
value counts : 0.768063    1559
0.231937     184
Name: const_neg, dtype: int64
_________________________________________________
tenencia
nunique : 6
value counts : 0.535257    837
0.149537    386
0.149912    327
0.128310    119
0.024841     66
0.012144      8
Name: tenencia, dtype: int64
_________________________________________________
computador
nunique : 2
value counts : 0.408921    1035
0.591079     708
Name: computador, dtype: int64
_________________________________________________
tel_fijo
nunique : 2
value counts : 0.492151    1266
0.507849     477
Name: tel_fijo, dtype: int64
_________________________________________________
celular
nunique : 2
value counts : 0.390854    1224
0.609146     519
Name: celular, dtype: int64
_________________________________________________
internet
nunique : 2
value counts : 0.433801    873
0.566199    870
Name: internet, dtype: int64
_________________________________________________
tv_paga
nunique : 2
value counts : 0.895129    1609
0.104871     134
Name: tv_paga, dtype: int64
_________________________________________________
auto_pick
nunique : 2
value counts : 0.519203    1003
0.480797     740
Name: auto_pick, dtype: int64
_________________________________________________
ent
nunique : 1
value counts : 9    1743
Name: ent, dtype: int64
_________________________________________________
mun
nunique : 16
value counts : 7     303
5     208
15    171
10    136
3     134
12    124
2     100
17     89
14     86
11     82
6      73
13     67
16     65
8      42
9      32
4      31
Name: mun, dtype: int64
_________________________________________________
loc
nunique : 14
value counts : 1      1685
21       10
17        8
56        7
324       5
27        5
20        5
11        5
26        4
134       3
239       2
161       2
228       1
227       1
Name: loc, dtype: int64
_________________________________________________
cuart_dorm
nunique : 8
value counts : 2    646
1    614
3    356
4     98
5     23
6      4
9      1
7      1
Name: cuart_dorm, dtype: int64
_________________________________________________
num_cuarto
nunique : 13
value counts : 4     485
5     369
3     347
2     164
6     160
1      81
7      69
8      34
9      14
10     11
11      5
16      2
12      2
Name: num_cuarto, dtype: int64
_________________________________________________
bano_comp
nunique : 8
value counts : 1    1122
2     279
0     229
3      75
4      26
5       7
6       4
7       1
Name: bano_comp, dtype: int64
_________________________________________________
bano_excus
nunique : 5
value counts : 0    1224
1     486
2      28
3       4
6       1
Name: bano_excus, dtype: int64
_________________________________________________
bano_regad
nunique : 2
value counts : 0    1729
1      14
Name: bano_regad, dtype: int64
_________________________________________________
focos_inca
nunique : 21
value counts : 0     1333
1       82
2       82
3       60
4       48
5       33
6       33
8       17
7       17
10      13
9        6
15       5
12       4
13       2
25       2
30       1
11       1
16       1
17       1
28       1
35       1
Name: focos_inca, dtype: int64
_________________________________________________
focos_ahor
nunique : 44
value counts : 6     214
5     197
4     188
8     149
7     142
3     135
10    126
0     116
2      83
9      72
1      45
15     38
12     37
20     34
11     28
13     21
14     20
30     19
25     12
16     11
18      6
40      5
50      5
17      4
21      4
23      4
22      3
60      3
35      3
19      2
31      2
99      2
26      2
29      1
28      1
90      1
33      1
36      1
37      1
45      1
46      1
24      1
70      1
32      1
Name: focos_ahor, dtype: int64
_________________________________________________
tot_resid
nunique : 15
value counts : 3     372
4     370
2     346
5     237
1     211
6     103
7      48
8      23
9      12
10      8
14      4
11      4
15      2
12      2
16      1
Name: tot_resid, dtype: int64
_________________________________________________
tot_hog
nunique : 4
value counts : 1    1721
2      16
3       5
4       1
Name: tot_hog, dtype: int64
_________________________________________________
tam_loc
nunique : 4
value counts : 1    1677
2      32
4      21
3      13
Name: tam_loc, dtype: int64
_________________________________________________
est_socio
nunique : 4
value counts : 3    783
2    687
4    268
1      5
Name: est_socio, dtype: int64
_________________________________________________