In [1]:
import pandas as pd

In [2]:
file = "../../dataframes/intercensal_persona.csv"

In [3]:
df = pd.read_csv(filepath_or_buffer=file)

In [4]:
df.shape

(553032, 47)

In [5]:
df.columns

Index(['Unnamed: 0', 'ID_VIV', 'ID_PERSONA', 'ENT', 'MUN', 'NOM_MUN', 'LOC50K',
       'NOM_LOC', 'COBERTURA', 'ESTRATO', 'UPM', 'FACTOR', 'NUMPER', 'SEXO',
       'EDAD', 'PARENT', 'PARENT_OTRO_C', 'IDENT_MADRE', 'IDENT_PADRE',
       'SERSALUD', 'AFRODES', 'ACTA_NAC', 'DHSERSAL1', 'PERTE_INDIGENA',
       'ENT_PAIS_NAC', 'NACIONALIDAD', 'HLENGUA', 'ELENGUA', 'ASISTEN',
       'ESCOLARI', 'NIVACAD', 'ALFABET', 'ESCOACUM', 'MUN_RES10',
       'NOM_MUN_RES10', 'ENT_PAIS_RES10', 'SITUA_CONYUGAL', 'CONACT',
       'ACTI_SIN_PAGO1', 'ACTI_SIN_PAGO2', 'ACTI_SIN_PAGO3', 'ACTI_SIN_PAGO4',
       'ACTI_SIN_PAGO5', 'ACTI_SIN_PAGO6', 'ACTI_SIN_PAGO7', 'ACTI_SIN_PAGO8',
       'TAMLOC'],
      dtype='object')

In [246]:
df_copy = df.copy()

In [247]:
l = ['Unnamed: 0', 'ID_VIV', 'ID_PERSONA','LOC50K', 'NOM_LOC', 'COBERTURA', 'UPM', 'FACTOR', 'NUMPER', 'PARENT_OTRO_C', 'IDENT_MADRE', 'IDENT_PADRE']

In [248]:
df_copy.drop_duplicates(inplace=True)

In [249]:
df_copy.shape

(553032, 47)

In [250]:
df_copy.drop(labels=l, axis=1, inplace=True)

In [251]:
df_copy.columns

Index(['ENT', 'MUN', 'NOM_MUN', 'ESTRATO', 'SEXO', 'EDAD', 'PARENT',
       'SERSALUD', 'AFRODES', 'ACTA_NAC', 'DHSERSAL1', 'PERTE_INDIGENA',
       'ENT_PAIS_NAC', 'NACIONALIDAD', 'HLENGUA', 'ELENGUA', 'ASISTEN',
       'ESCOLARI', 'NIVACAD', 'ALFABET', 'ESCOACUM', 'MUN_RES10',
       'NOM_MUN_RES10', 'ENT_PAIS_RES10', 'SITUA_CONYUGAL', 'CONACT',
       'ACTI_SIN_PAGO1', 'ACTI_SIN_PAGO2', 'ACTI_SIN_PAGO3', 'ACTI_SIN_PAGO4',
       'ACTI_SIN_PAGO5', 'ACTI_SIN_PAGO6', 'ACTI_SIN_PAGO7', 'ACTI_SIN_PAGO8',
       'TAMLOC'],
      dtype='object')

In [252]:
df_copy.isnull().any().any()

True

In [253]:
df_copy.columns[df_copy.isnull().any()]

Index(['HLENGUA', 'ELENGUA', 'ASISTEN', 'ESCOLARI', 'NIVACAD', 'ALFABET',
       'ESCOACUM', 'MUN_RES10', 'NOM_MUN_RES10', 'ENT_PAIS_RES10',
       'SITUA_CONYUGAL', 'CONACT', 'ACTI_SIN_PAGO1', 'ACTI_SIN_PAGO2',
       'ACTI_SIN_PAGO3', 'ACTI_SIN_PAGO4', 'ACTI_SIN_PAGO5', 'ACTI_SIN_PAGO6',
       'ACTI_SIN_PAGO7', 'ACTI_SIN_PAGO8'],
      dtype='object')

In [254]:
len(pd.isnull(df_copy).any(1).nonzero()[0].tolist())

102361

In [255]:
df_copy.dropna(inplace=True)

In [256]:
df_copy.reset_index(inplace=True)

In [258]:
df_copy.drop(labels=['index'], axis=1, inplace=True)

In [259]:
df_copy.head()

,ENT,MUN,NOM_MUN,ESTRATO,SEXO,EDAD,PARENT,SERSALUD,AFRODES,ACTA_NAC,...,CONACT,ACTI_SIN_PAGO1,ACTI_SIN_PAGO2,ACTI_SIN_PAGO3,ACTI_SIN_PAGO4,ACTI_SIN_PAGO5,ACTI_SIN_PAGO6,ACTI_SIN_PAGO7,ACTI_SIN_PAGO8,TAMLOC
0,9,2,Azcapotzalco,09-002-02,1,18,8,7,3,1,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,5
1,9,2,Azcapotzalco,09-002-03,3,81,1,1,3,1,...,33.0,0.0,0.0,0.0,0.0,0.0,35.0,10.0,2.0,5
2,9,2,Azcapotzalco,09-002-02,3,49,2,1,3,2,...,33.0,0.0,0.0,0.0,25.0,0.0,10.0,50.0,16.0,5
3,9,2,Azcapotzalco,09-002-02,1,54,1,1,3,1,...,10.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,3.0,5
4,9,2,Azcapotzalco,09-002-02,1,26,3,1,3,1,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5

In [260]:
df_copy.shape

(450671, 35)

In [261]:
numericos = ['EDAD']

In [262]:
categoricos = []

for row in df_copy.columns:
    if row not in numericos:
        if (row != 'ENT') & (row != 'MUN') & (row != 'NOM_MUN') :
#            print(row)
            categoricos.append(row)

In [263]:
for line in df_copy.columns:
    print(line, ' : ', df_copy[line].unique(), '\n')

ENT  :  [9]

MUN  :  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

NOM_MUN  :  ['Azcapotzalco' 'Coyoacán' 'Cuajimalpa de Morelos' 'Gustavo A. Madero'
 'Iztacalco' 'Iztapalapa' 'La Magdalena Contreras' 'Milpa Alta'
 'Álvaro Obregón' 'Tláhuac' 'Tlalpan' 'Xochimilco' 'Benito Juárez'
 'Cuauhtémoc' 'Miguel Hidalgo' 'Venustiano Carranza']

ESTRATO  :  ['09-002-02' '09-002-03' '09-002-04' '09-002-01' '09-002-05' '09-003-03'
 '09-003-04' '09-003-02' '09-003-01' '09-003-05' '09-004-03' '09-004-04'
 '09-004-02' '09-004-01' '09-004-06' '09-004-09' '09-004-08' '09-004-05'
 '09-004-10' '09-004-07' '09-005-05' '09-005-02' '09-005-07' '09-005-04'
 '09-005-03' '09-005-08' '09-005-06' '09-005-01' '09-005-09' '09-006-02'
 '09-006-01' '09-006-03' '09-006-04' '09-007-02' '09-007-06' '09-007-05'
 '09-007-01' '09-007-04' '09-007-07' '09-007-08' '09-007-03' '09-007-11'
 '09-008-03' '09-008-04' '09-008-01' '09-008-06' '09-008-02' '09-008-05'
 '09-009-05' '09-009-18' '09-009-12' '09-009-17' '09-009-07' '09-009-02'
 '09-009-04' '09-009-06' '09-009-15' '09-009-16' '09-009-08' '09-009-01'
 '09-009-14' '09-009-03' '09-009-11' '09-009-09' '09-009-13' '09-009-10'
 '09-010-01' '09-010-05' '09-010-07' '09-010-02' '09-010-04' '09-010-08'
 '09-010-03' '09-010-06' '09-010-10' '09-011-11' '09-011-01' '09-011-08'
 '09-011-03' '09-011-10' '09-011-02' '09-011-12' '09-011-09' '09-011-07'
 '09-011-06' '09-011-13' '09-011-04' '09-011-05' '09-012-03' '09-012-07'
 '09-012-22' '09-012-02' '09-012-01' '09-012-05' '09-012-18' '09-012-31'
 '09-012-28' '09-012-04' '09-012-27' '09-012-24' '09-012-20' '09-012-14'
 '09-012-10' '09-012-19' '09-012-30' '09-012-21' '09-012-06' '09-012-12'
 '09-012-11' '09-012-15' '09-012-23' '09-012-17' '09-012-26' '09-012-13'
 '09-012-29' '09-012-08' '09-012-25' '09-012-16' '09-013-01' '09-013-09'
 '09-013-02' '09-013-03' '09-013-04' '09-013-10' '09-013-06' '09-013-08'
 '09-013-05' '09-013-07' '09-014-02' '09-014-01' '09-015-03' '09-015-02'
 '09-015-04' '09-015-01' '09-015-05' '09-016-02' '09-016-03' '09-016-01'
 '09-016-04' '09-016-05' '09-017-02' '09-017-03' '09-017-04' '09-017-01'
 '09-017-05']

SEXO  :  [1 3]

EDAD  :  [ 18  81  49  54  26  27  50  44  40  53  22  32  28  29  57  24  51  55
  58  31  47  83  45  61  23  56  60  76  52  65  63  25  34  12  36  37
  70  48  74  85  42  16  41  33  14  17  21  62  64  19  15  20  88  77
  43  82  72  59  86  35  66  30  38  46  13  69  73  79  71  39  68  75
  67  80  84  89  87  78  94  93  91  90  96 999  92  95  97 101 100  98
 103  99 104 102 105 106]

PARENT  :  [ 8  1  2  3  5  4  7  9  6 99]

SERSALUD  :  [ 7  1  6  5  2  4  8  3  9 99]

AFRODES  :  [3 1 8 9 2]

ACTA_NAC  :  [1 2 3 9]

DHSERSAL1  :  [8 2 1 3 6 5 7 4 9]

PERTE_INDIGENA  :  [1 3 8 2 9]

ENT_PAIS_NAC  :  [ 13   9  15  16  30  24  12 999   7  11  14 214  29  26  27  28 229  31
   2  32  21   5  25  20 215  10  17  23 221 415   1  22   4 352 250 316
  19   8 239 419  18 225   6 343 217 210   3 216 237 330 425 439 204 315
 442 220 335 238 437 219 211 247 228 423 402 313 418 998 325 438 441 445
 213 234 347 436 117 329 235 236 440 446 349 408 411 447 501 142 405 410
 102 126 322 422 416 169 303 428 312 129 341 421 208 124 354 161 327 135
 164 326 353 154 109]

NACIONALIDAD  :  [5 9 7]

HLENGUA  :  [3. 9.]

ELENGUA  :  [3. 9. 1.]

ASISTEN  :  [7. 5. 9.]

ESCOLARI  :  [ 3.  6.  5.  2.  4.  1.  0. 99.  8.  7.]

NIVACAD  :  [ 3.  2.  4. 11.  5.  7. 12. 13. 10.  0. 99.  8. 14.  6.  9.  1.]

ALFABET  :  [5. 7. 9.]

ESCOACUM  :  [ 9.  6.  5.  8. 12. 16. 17. 11. 19. 14.  1. 13.  3.  2.  7.  0. 10. 15.
 99. 18. 24.  4. 20. 21. 22. 23.]

MUN_RES10  :  [  2.  17.  31.  53. 108.  15. 104. 109.  60.  24.   5.  39.  33.  16.
 999.  12.  69.  57.  10.  25.  14.  11.   7.  81.  20.  76. 114. 106.
   4.  35.  58.  26.  29.  54.  13.   8.   3.   1. 122.   6. 121.  19.
  28.  56.  91. 100.  87. 154. 182. 138.  46.  67.  44. 193. 120.  22.
 116. 156. 164. 112.  32. 134.  50.  48. 162.  37. 160.  95. 208. 101.
  94. 177.  92.  51.  49.  47.  77.  80.  99. 183.  18.  41.  82.  34.
   9.  38.  45.  78. 324. 173.  59. 128. 113. 140. 150.  42. 124.  27.
  75. 197. 482. 212. 131.  55.  71.  21.  52.  89.  97. 110.  61. 118.
 549.  63.  66.  74.  62.  88. 132. 102. 107.  98.  30. 313.  93.  86.
 117. 111. 180.  70. 174.  36.  65. 167.  73.  43. 364. 204. 189. 304.
 318.  23. 119. 163. 184.  96.  90. 397. 413. 350. 213.  68. 199.  84.
 103.  85.  64. 149. 567. 141. 221. 105. 143. 207. 515. 401. 331.  40.
 559. 158. 209.  79. 312. 545. 115. 200.  72. 391. 211. 277. 361.  83.
 186. 142. 172. 157. 551. 125. 412. 404. 525. 178. 169. 130. 570. 175.
 126. 315. 339. 196. 155. 129. 414. 152. 166. 263. 418. 194. 266.]

NOM_MUN_RES10  :  ['Acaxochitlán' 'Azcapotzalco' 'Venustiano Carranza' 'Chimalhuacán'
 'Morelia' 'Tultepec' 'Guanajuato' 'Tlalnepantla de Baz' 'Tultitlán'
 'Nicolás Romero' 'Cuautitlán' 'Gustavo A. Madero' 'Guadalajara'
 'Ecatepec de Morelos' 'Miguel Hidalgo'
 'No especificado de Entidad y Municipio' 'Atizapán' 'Tizayuca'
 'San Francisco del Rincón' 'Naucalpan de Juárez' 'Álvaro Obregón'
 'Colima' 'Chalco' 'Benito Juárez' 'Tlalpan' 'Cuauhtémoc' 'Tláhuac'
 'Iztapalapa' 'Tecámac' 'Coacalco de Berriozábal' 'Tula de Allende'
 'Mazatlán' 'Puebla' 'Toluca' 'Cuajimalpa de Morelos' 'Tarimoro' 'Celaya'
 'Huehuetoca' 'Nezahualcóyotl' 'Chapa de Mota' 'Chilpancingo de los Bravo'
 'Metepec' 'Atizapán de Zaragoza' 'La Magdalena Contreras' 'Cuernavaca'
 'Querétaro' 'Tijuana' 'Coyoacán' 'Acapulco de Juárez'
 'Valle de Chalco Solidaridad' 'Monterrey' 'Iztacalco'
 'Cuautitlán Izcalli' 'Atlixco' 'Ixtapaluca' 'Almoloya de Juárez'
 'San Luis Potosí' 'Fresnillo' 'Zacatecas' 'Xochimilco' 'Teoloyucan'
 'Tezoyuca' 'Xalapa' 'Culiacán' 'Tecamachalco' 'Tlanepantla' 'Río Blanco'
 'Guaymas' 'San Nicolás de los Garza' 'Puerto Vallarta' 'Guasave'
 'Zacatelco' 'Veracruz' 'Zumpango' 'Coyuca de Catalán' 'Quimixtlán'
 'Tehuacán' 'Apizaco' 'Oaxaca de Juárez' 'Chihuahua' 'Jilotzingo'
 'Aguascalientes' 'Matamoros' 'Tepeaca' 'Villa del Carbón' 'Reynosa'
 'Chicoloapan' 'San Matías Tlalancaleca' 'Nacajuca'
 'Matías Romero Avendaño' 'Othón P. Blanco' 'Zapopan' 'Miacatlán' 'Mérida'
 'Coatzacoalcos' 'Pachuca de Soto' 'Irapuato' 'Tlaxcala' 'León'
 'Tepango de Rodríguez' 'Huixquilucan' 'La Paz' 'Álamo Temapache' 'Apaxco'
 'Tepotzotlán' 'Manzanillo' 'Jojutla' 'Zacatlán' 'Boca del Río'
 'Tamazunchale' 'Tuxtla Gutiérrez' 'Centro' 'San Juan del Río' 'Los Cabos'
 'Jocotitlán' 'Libres' 'Tlacotepec de Benito Juárez' 'Matehuala'
 'Teotihuacán' 'Lerma' 'Santa Cruz de Juventino Rosas' 'Joquicingo'
 'Torreón' 'Chiautla' 'Tulancingo de Bravo' 'Sultepec' 'Texcoco'
 'Nopala de Villagrán' 'Zamora' 'Iguala de la Independencia' 'Tlapacoyan'
 'Villa Victoria' 'Actopan' 'Navolato' 'Victoria' 'Tejupilco' 'Hidalgo'
 'Atlacomulco' 'Milpa Alta' 'Zihuatanejo de Azueta' 'Durango' 'Tepoztlán'
 'San Blas' 'Chalchicomula de Sesma' 'San Cristóbal de las Casas'
 'San Pedro Pochutla' 'Hueytamalco' 'Chilapa de Álvarez' 'Sinaloa'
 'Tezonapa' 'Huimanguillo' 'Miahuatlán de Porfirio Díaz' 'Chilchotla'
 'Perote' 'Villa Guerrero' 'Tonalá' 'Heroica Ciudad de Huajuapan de León'
 'San Pedro Cholula' 'San Francisco Telixtlahuaca' 'Valle de Santiago'
 'San José del Rincón' 'Autlán de Navarro' 'Acolman'
 'Tetla de la Solidaridad' 'Corregidora' 'Solidaridad' 'Ario'
 'Chiapa de Corzo' 'Ahome' 'Zitácuaro' 'Los Reyes' 'Tocatlán' 'Campeche'
 'Xicotepec' 'Yautepec' 'Jalapa' 'Tlaxco' 'Siltepec' 'Tampico'
 'Santiago Pinotepa Nacional' 'Cuautla' 'Atoyac de Álvarez' 'Zautla'
 'Mixquiahuala de Juárez' 'Poza Rica de Hidalgo' 'Cuautlancingo' 'Apan'
 'Taxco de Alarcón' 'Mexicali' 'Juárez' 'Huatusco' 'Delicias' 'Amatepec'
 'Ayahualulco' 'Juchitlán' 'Tapachula' 'Tlajomulco de Zúñiga' 'Ensenada'
 'Tlapehuala' 'Chiconcuautla' 'Valle de Bravo' 'Ocampo' 'Huamantla'
 'Orizaba' 'Mazamitla' 'Maravatío'
 'Heroica Villa Tezoatlán de Segura y Luna, Cuna de la Independencia de Oaxaca'
 'Altotonga' 'Tepeji del Río de Ocampo' 'San Pedro Garza García'
 'Pátzcuaro' 'Huichapan' 'Xico' 'San Felipe del Progreso' 'Tianguistenco'
 'Calimaya' 'Córdoba' 'Ocoyoacac' 'La Piedad' 'Tenancingo' 'Monclova'
 'Eduardo Neri' 'Jiquipilco' 'San Martín Texmelucan' 'Coatepec Harinas'
 'Martínez de la Torre' 'Tonatico' 'Tuxpan' 'Tetela del Volcán'
 'Chiconcuac' 'Acambay de Ruíz Castañeda' 'Ciudad Valles' 'Guadalupe'
 'Comitán de Domínguez' 'Papantla' 'Abasolo' 'Ocuilan' 'Saltillo'
 'Chichiquila' 'Huetamo' 'Teteles de Avila Castillo' 'Atempan'
 'San Pedro Jocotipac' 'Tlalpujahua' 'Ixtlahuaca' 'Jalacingo'
 'Chiautzingo' 'Montecristo de Guerrero' 'Santa Catarina'
 'San Mateo Atenco' 'Villa de Allende' 'Hermosillo'
 'Tlaltizapán de Zapata' 'Tepecoacuilco de Trujano' 'Coscomatepec'
 'San Luis Río Colorado' 'Acámbaro' 'Temoaya' 'Uruapan' 'Rioverde'
 'Dolores Hidalgo Cuna de la Independencia Nacional' 'Tlachichilco'
 'Metztitlán' 'Arcelia' 'Malinalco' 'Ajuchitlán del Progreso' 'Teziutlán'
 'Nuevo Laredo' 'Cerro Azul' 'Cuautepec de Hinojosa' 'Hueypoxtla'
 'Arandas' 'Tamalín' 'Otumba' 'Santiago de Anaya' 'Tepetzintla'
 'Comalcalco' 'Aculco' 'Minatitlán' 'Ixmiquilpan' 'San Fernando'
 'Coahuitlán' 'Acula' 'Panotla' 'San Juan de los Lagos' 'Xochiatipan'
 'Nicolás Flores' 'Huejutla de Reyes' 'Bahía de Banderas'
 'Santa Catarina Juquila' 'Agua Dulce' 'Loma Bonita' 'San Antonio la Isla'
 'San Pedro Coxcaltepec Cántaros' 'San Pedro Mixtepec' 'Huauchinango'
 'Chiautempan' 'Piedras Negras' 'Ahuazotepec' 'Coyotepec' 'Chignahuapan'
 'Villa de Tezontepec' 'San Andrés Cholula' 'Tepic' 'Angel R. Cabada'
 'Acacoyagua' 'Tenochtitlán' 'San Juan Bautista Tuxtepec' 'Tequixquiac'
 'Cosamaloapan de Carpio' 'Cozumel' 'Mapastepec' 'Progreso de Obregón'
 'Cuitláhuac' 'Chontla' 'Puruándiro' 'Alfajayucan' 'Tenango del Valle'
 'Xichú' 'Lázaro Cárdenas' 'Jilotepec' 'Carmen' 'Cohetzala' 'San Pedro'
 'Bacalar' 'Tezontepec de Aldama' 'Zinacantepec' 'Tlahuiltepa' 'Zacapu'
 'Cuetzala del Progreso' 'Eloxochitlán' 'Ixcateopan de Cuauhtémoc'
 'Zinapécuaro' 'Nochistlán de Mejía' 'Santa Cruz Tlaxcala' 'Acatepec'
 'Marquelia' 'El Arenal' 'Francisco I. Madero'
 'Heroica Ciudad de Tlaxiaco' 'San Martín de las Pirámides' 'Amecameca'
 'Santa María Huatulco' 'Asunción Nochixtlán' 'Cuitzeo' 'Morelos'
 'Naranjos Amatlán' 'Ciudad Madero' 'San Sebastián Tutla' 'Jesús María'
 'Temascaltepec' 'Tierra Blanca' 'Apodaca' 'Contepec' 'Zihuateutla'
 'Ecatzingo' 'Cuajinicuilapa' 'La Huerta' 'San Pablo del Monte'
 'Zacualtipán de Ángeles' 'Fortín' 'Tlapa de Comonfort' 'Ocosingo'
 'Axapusco' 'Xiutetelco' 'Texcaltitlán' 'Zimapán' 'Tlalmanalco' 'Turicato'
 'Ozumba' 'Pantepec' 'Izúcar de Matamoros' 'Cuyamecalco Villa de Zaragoza'
 'San Juan Bautista Cuicatlán' 'Cocula' 'San Lucas Tecopilco'
 'Francisco Z. Mena' 'Cocotitlán' 'Soteapan' 'Zapotitlán Lagunas'
 'San Andrés Tuxtla' 'Ojuelos de Jalisco' 'Azoyú' 'San Juan Teposcolula'
 'Angangueo' 'Tlatlaya' 'Acultzingo' 'Santiago Tuxtla' 'Jiutepec'
 'Emiliano Zapata' 'Zacapoaxtla' 'Tepalcingo' 'Lafragua' 'Moctezuma'
 'Lagunillas' 'Santo Domingo Tehuantepec' 'El Oro' 'Santa María Colotepec'
 'Tepatitlán de Morelos' 'Alvarado' 'Isla' 'San Pedro Tidaá' 'Temixco'
 'Huitzuco de los Figueroa' 'Chalcatongo de Hidalgo' 'Ixtapan de la Sal'
 'Coyuca de Benítez' 'Ixtapa' 'Progreso' 'Huejotzingo' 'Totolapan'
 'San Juan Bautista Valle Nacional' 'Las Margaritas' 'Tres Valles'
 'Tecolutla' 'Acatzingo' 'Amatitlán' 'Atlatlahucan' 'Zapotitlán'
 'Ahualulco de Mercado' 'Playas de Rosarito' 'Ixtapan del Oro' 'Ayapango'
 'Puerto Peñasco' 'Atenco' 'Cadereyta de Montes' 'Quechultenango'
 'Alpatláhuac' 'Comondú' 'San Salvador el Verde' 'San José Iturbide'
 'Tlalchapa' 'Rodeo' 'Las Vigas de Ramírez' 'Coroneo' 'Tlahuapan'
 'Salina Cruz' 'Amacuzac' 'Igualapa' 'Xaltocan' 'Montemorelos'
 'Ixtlahuacán de los Membrillos' 'Calnali' 'San Pedro Jicayán' 'Zacatepec'
 'Teotitlán de Flores Magón' 'Caltepec' 'Senguio' 'Tecozautla'
 'Chapulhuacán' 'Maravilla Tenejapa' 'Tizimín' 'Tepetlixpa'
 'Mariano Escobedo' 'Tlalnepantla' 'Acaponeta' 'San Andrés Zautla'
 'Palmar de Bravo' 'Jungapeo' 'Copala' 'Xochiapulco' 'Espinal' 'Huehuetla'
 'Santa Lucía Miahuatlán' 'Catemaco' 'Donato Guerra' 'Pinal de Amoles'
 'Buenavista' 'Nejapa de Madero' 'Nopaltepec' 'Otzolotepec' 'Zaragoza'
 'Temascalcingo' 'Xochitepec' 'Villa Sola de Vega' 'Santa Catalina Quierí'
 'Tala' 'Villa de Álvarez' 'Tlatlauquitepec' 'Teocelo' 'Cuapiaxtla'
 'San Miguel de Allende' 'San Juan Evangelista' 'Ajacuba' 'Cosoleacaque'
 'Nextlalpan' 'Ayotlán' 'Nautla' 'Coatepec' 'Acajete' 'El Marqués'
 'San Andrés Huaxpaltepec' 'Ameca' 'Tetela de Ocampo' 'Coatlán del Río'
 'Zacualpan' 'Castillo de Teayo' 'Xalpatláhuac' 'Ayutla de los Libres'
 'Apaseo el Grande' 'Ometepec' 'Pénjamo' 'Juchitepec'
 'Putla Villa de Guerrero' 'San Miguel Totolapan' 'Altamira' 'Calcahualco'
 'San Juan Mazatlán' 'Isla Mujeres' 'Domingo Arenas' 'Salamanca' 'Linares'
 'Apatzingán' 'Juárez Hidalgo' 'Pungarabato' 'Juan Rodríguez Clara'
 'Alcozauca de Guerrero' 'Silao de la Victoria' 'Cuautepec' 'Doctor Mora'
 'San Felipe' 'Tlacolula de Matamoros' 'Mulegé' 'Tonanitla'
 'Santa María Guienagati' 'Huitzilac' 'Tenango de Doria' 'Valladolid'
 'Atlixtac' 'Cárdenas' 'Santa María Chachoápam' 'Aquixtla' 'Peñamiller'
 'Santo Domingo Zanatepec' 'Tlacuilotepec' 'José Azueta' 'Paraíso'
 'Nogales' 'Jonacatepec' 'Yecapixtla' 'Amanalco' 'Ciudad Ixtepec'
 'Chapantongo' 'Playa Vicente' 'Zimatlán de Álvarez' 'Tihuatlán'
 'Paso de Ovejas' 'San Luis Acatlán' 'Tenampulco' 'Tepeapulco'
 'San Pedro Mártir' 'Oriental' 'Comonfort' 'Tlapacoya' 'Lagos de Moreno'
 'Hueyapan' 'Castaños' 'Misantla' 'Chignautla' 'Tlaola' 'Puente de Ixtla'
 'Capulhuac' 'Omealca' 'Juan Galindo' 'Escárcega' 'Cuyoaco' 'Arroyo Seco'
 'El Porvenir' 'Palenque' 'Tecate' 'Sahuayo' 'Tequila' 'Apazapan'
 'Amealco de Bonfil' 'Yecuatla' 'Umán' 'El Mante' 'Cajeme'
 'San Pedro y San Pablo Teposcolula' 'Amaxac de Guerrero'
 'San Juan de Sabinas' 'San Pedro Tlaquepaque' 'Río Grande' 'Yanga'
 'Zapotlanejo' 'Paso del Macho' 'Arriaga' 'Jerécuaro' 'Tantoyuca'
 'Caborca' 'Almoloya' 'Gómez Palacio' 'Nuevo Ideal' 'La Antigua'
 'Ocotlán de Morelos' 'Angostura' 'Trincheras'
 'Soledad de Graciano Sánchez' 'Carrillo Puerto' 'San José Miahuatlán'
 'Teapa' 'Atitalaquia' 'Técpan de Galeana' 'Tepehuacán de Guerrero'
 'Tenampa' 'Jaltenco' 'Tepatlaxco de Hidalgo' 'Jiquilpan' 'Coronango'
 'El Espinal' 'Atlangatepec' 'Tamazula' 'Quintana Roo'
 'Heroica Ciudad de Juchitán de Zaragoza' 'Epitacio Huerta'
 'Santa María Huazolotitlán' 'Atlautla' 'Muna' 'Ramos Arizpe'
 'Tlahuelilpan' 'Ixtacamaxtitlán' 'Agua Prieta' 'Anáhuac'
 'Cuetzalan del Progreso' 'Epazoyucan' 'Xicoténcatl' 'Huatabampo'
 'Temamatla' 'Zempoala' 'Natívitas' 'Gabriel Zamora' 'Tampico Alto'
 'San José Chiltepec' 'San Luis de la Paz' 'Calpulalpan' 'Jopala'
 'San Miguel Coatlán' 'Terrenate' 'Atltzayanca'
 'Santa María Jalapa del Marqués' 'Naolinco' 'San Salvador el Seco'
 'Tianguistengo' 'Amozoc' 'Carlos A. Carrillo' 'Moroleón'
 'San Felipe Teotlalcingo' 'Villa Aldama' 'General Heliodoro Castillo'
 'Atoyac' 'Tecalitlán' 'San Rafael' 'Tamasopo' 'San Miguel del Puerto'
 'Ciudad Fernández' 'El Salto' 'Asunción Ocotlán']

ENT_PAIS_RES10  :  [ 13.   9.  15.  16.  11.  14.  29. 999.   6.  17.   2.  20.  25.  12.
  21.  22.  19.  31.  24.  32.  30.  26.   7.   8.   1.  28.  23.  27.
  18.   3.   5.  10.   4.]

SITUA_CONYUGAL  :  [6. 4. 5. 1. 2. 3. 9.]

CONACT  :  [10. 33. 31. 32. 35. 20. 34. 15. 12. 11. 99. 16. 14. 13.]

ACTI_SIN_PAGO1  :  [  0.   4.   2.  48. 999.   5.  42.  17.   6.   8.  15.   1.   3.   7.
  28. 140.  60.  56.  21.  84.  14. 105.  24.  11.  10.  12.  50. 100.
  30. 112.  70.  45.  40.  25.  20. 126. 125.  80.  72.  43.  55.  91.
  35.  98. 131.  44.  18.  49. 124.  78.  64. 120.  62.  16.  68.  58.
  36.   9.  90.  26.  34.  32.  75. 114.  63.  92.  95.  69.  13.  77.
  94.  52.  23. 115.  29.  22. 110. 102.  76.  38.  96.  53.  81.  88.
  59.  86.  87.  82.  27.  54.  79. 130. 128.  71.  19. 119.  31. 104.
  85.  41.  46.  67.  57. 132.  74.  83.  47. 133.  33.  65. 108.  66.
 116. 117.  97. 135.  93.]

ACTI_SIN_PAGO2  :  [  0.  30. 999.  10.   1.   3.  15.  24.  17.   4.  28. 140.  70.   7.
 112.  20.   5.  25.  21.  60.   2. 105.   8.  35.  14.  90.  50. 100.
  80.  12.  56.  45.  42.  40.   6.  39.  48.  43.  55.   9.  98.  64.
  27.  72.  91.  84. 131.  44. 120.  33.  36.  54.  49.  85.  68.  58.
  16.  32.  94. 114. 126.  92.  26.  96.  69.  34.  63.  13. 124. 125.
  78.  52. 115.  29.  18.  22. 110.  82.  38.  66.  81.  88. 119.  59.
  46.  75.  11.  77.  23. 130.  74. 104.  79.  86.  76.  19. 132. 108.
 133. 118.  95. 138. 128.  57. 117.  62.]

ACTI_SIN_PAGO3  :  [  0.  15.  30.  42.  12. 999.  14.  20.  70.  10.  21.  40.   8.  18.
  35.  28.  50.   4.   5.  48.  60.   2.   6.  25.  36. 100.   1.  80.
  24.  65.  75.  56.  90.   3.  98.  84.  26.  29.   7. 140.  72.  78.
  13.  49. 112.  41.  82.  77.  63. 105.  73.  16. 126.  58.  45.  54.
 130.   9.  61.  68.  64. 110.  11. 118.  52. 104.  85.  86. 120.  38.
  74.  59.  27. 124.  19.  71.  34.  83. 133.  23.  33.  31.  94.  43.
  88.  39. 108.  76. 135.  95.  69.  32. 138. 116.  96. 125.  46.  91.
  22.  17.  67. 136. 132.  53.  93. 119.  47. 128.  55. 121.  62.  66.
 123.  44. 114.  99. 102. 115.  92.  81.  97.  79.  89. 106. 134.  51.
 103. 122.  57.  37.  87. 101. 113. 107. 109. 117. 111.]

ACTI_SIN_PAGO4  :  [  0.  25.  45.  70.  24. 999.  20.  21.   2.  42.  35.  40.  30.  60.
  28.  56.   5.   4.  14.   6.  11.   9.  48.  10.  93.  58.  19.  50.
  80.  15.  26.  12.   7.   3.  16. 100.   1.   8.  18. 140. 104.  57.
  36.  84.  68.  49.  13.  32.  38.  54.  72.  46.  90.  82.  39.  64.
  73.  83. 105. 112.  17. 118.  63.  61. 120. 108.  78.  98.  88.  74.
  55.  67.  91.  27.  29.  76.  37.  59.  22.  69.  75.  66. 124.  47.
  94.  34. 135. 130.  96.  52.  99.  23. 125. 128.  51.  77.  92.  44.
 132.  53.  65. 102. 126.  41. 121.  33.  31.  97.  95.  62.  85. 123.
 110. 133. 115.  71.  43.  89.  81. 116. 129.  86. 119. 103.  79. 101.
  87. 136. 113. 139. 114. 107. 138. 117.]

ACTI_SIN_PAGO5  :  [  0.  12. 999.   5.   3.  10.  20.  15.   2.   8.  17.  70.   6.   1.
  14.  50.  42.  52.   7. 110.  35.  48.   4.  24.  21.  28.   9. 140.
  18.  26.  30. 105.  25.  36.  60.  40.  80.  56. 108.  63. 100.  45.
  73. 126. 125.  95.  84.  49.  16.  98. 112.  43.  72.  44.  76.  11.
 106.  90. 131. 120.  33.  91.  94.  86.  96.  32.  54.  64.  78.  34.
  68.  58.  27.  75.  22.  13.  92.  82.  69.  41.  74. 128.  47.  88.
 130. 116.  29.  53.  81.  19.  65.  79.  62.  23. 114.  39.  38. 119.
 138.  55.  93.  85.  77. 113.  59. 104. 135.  57. 124.  37. 115. 136.
  46.  31.]

ACTI_SIN_PAGO6  :  [  0.  35.  10.   7.  28.  14.   2.   8.  20. 999.   5.   4.  25.  21.
  40.   6.  30.   1.   3.  12.  50.  17.  15.  13.  33.  18.  48.  16.
  42.  72.  80.  60.   9.  70.  90.  24.  52.  23.  19. 100.  49.  84.
  22.  11.  37.  32.  27. 120.  26.  38. 105.  54.  36.  56.  41.  85.
  45.  68.  92. 130.  55.  95.  44.  65. 140.  29.  69. 125.  75.  76.
  82.  34.  63.  46.  78.  86.  64.  58.  62.  53.  47.  81.  83.  94.
  43. 112. 110.  66. 122.  31. 126. 115.  98. 124.  77. 113.  74.  73.
  91.  57.  96.  39.  59. 133.  79.  51.  67. 121.  71.  61. 108. 136.]

ACTI_SIN_PAGO7  :  [  3.  10.  50.   0.   7.   4.  25.   5.  18.   2.  20.  21. 999.   1.
   8.  40.  24.  14.  28.  12.   6.  35.   9.  16.  48.  15.  45.  60.
  42.  49.  90.  52.  80.  30.  11.  56.  72.  23.  27.  98.  36.  17.
 100.  70.  32. 130.  22.  13. 120. 105.  26.  76.  84.  19.  54.  58.
  63.  92.  46. 140.  55.  69.  33.  31.  82.  44.  29.  86.  38.  37.
  41.  47. 108.  34.  39. 114.  97.  62.  75.  68.  64.  77.  94.  43.
 112.  51. 110. 126.  66. 113.  53. 132.  78.  96. 111.  74.  65.  59.
  83. 118.  99.  57.  81.  71.  85. 124.]

ACTI_SIN_PAGO8  :  [  2.  16.   3.   0.   7.   4.   5.   1.   8. 999.   6.  10.  14.  30.
  12.  48.  21.  24.  20.  29.  15.  80.   9.  35.  50.  28.  11.  18.
  40.  42.  27. 105.  25.  70.  13.  54. 120.  36.  32. 130.  90.  19.

In [264]:
df_copy.ESTRATO[1]

'09-002-03'

In [265]:
l_estrato = []
for line in range(0, df_copy.shape[0]):
    l_estrato.append(df_copy.ESTRATO[line][7:])

In [266]:
df_copy.shape

(450671, 35)

In [267]:
df_copy.head()

,ENT,MUN,NOM_MUN,ESTRATO,SEXO,EDAD,PARENT,SERSALUD,AFRODES,ACTA_NAC,...,CONACT,ACTI_SIN_PAGO1,ACTI_SIN_PAGO2,ACTI_SIN_PAGO3,ACTI_SIN_PAGO4,ACTI_SIN_PAGO5,ACTI_SIN_PAGO6,ACTI_SIN_PAGO7,ACTI_SIN_PAGO8,TAMLOC
0,9,2,Azcapotzalco,09-002-02,1,18,8,7,3,1,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,5
1,9,2,Azcapotzalco,09-002-03,3,81,1,1,3,1,...,33.0,0.0,0.0,0.0,0.0,0.0,35.0,10.0,2.0,5
2,9,2,Azcapotzalco,09-002-02,3,49,2,1,3,2,...,33.0,0.0,0.0,0.0,25.0,0.0,10.0,50.0,16.0,5
3,9,2,Azcapotzalco,09-002-02,1,54,1,1,3,1,...,10.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,3.0,5
4,9,2,Azcapotzalco,09-002-02,1,26,3,1,3,1,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5

In [268]:
len(l_estrato)

450671

In [269]:
df_copy.ESTRATO = l_estrato

In [270]:
df_copy.ESTRATO.value_counts()

02    120617
03     97565
04     72860
01     62230
05     38652
07     22357
06     15525
18      4979
08      2475
12      1897
09      1297
17      1190
10      1140
11       944
31       753
13       747
21       737
30       626
16       620
19       453
14       416
24       413
28       398
22       330
23       325
15       280
27       227
26       208
29       173
20       160
25        77
Name: ESTRATO, dtype: int64

In [271]:
l_og = []
for line in df_copy.columns:
    print(line, ' : ', df_copy[line].nunique(), '\n')
    l_og.append(df_copy[line].nunique())

ENT  :  1

MUN  :  16

NOM_MUN  :  16

ESTRATO  :  31

SEXO  :  2

EDAD  :  96

PARENT  :  10

SERSALUD  :  10

AFRODES  :  5

ACTA_NAC  :  4

DHSERSAL1  :  9

PERTE_INDIGENA  :  5

ENT_PAIS_NAC  :  113

NACIONALIDAD  :  3

HLENGUA  :  2

ELENGUA  :  3

ASISTEN  :  3

ESCOLARI  :  10

NIVACAD  :  16

ALFABET  :  3

ESCOACUM  :  26

MUN_RES10  :  209

NOM_MUN_RES10  :  657

ENT_PAIS_RES10  :  33

SITUA_CONYUGAL  :  7

CONACT  :  14

ACTI_SIN_PAGO1  :  117

ACTI_SIN_PAGO2  :  106

ACTI_SIN_PAGO3  :  137

ACTI_SIN_PAGO4  :  134

ACTI_SIN_PAGO5  :  114

ACTI_SIN_PAGO6  :  112

ACTI_SIN_PAGO7  :  106

ACTI_SIN_PAGO8  :  92

TAMLOC  :  4

In [272]:
for element in categoricos:
    column = element
    
    print(element)

    grouped = pd.DataFrame(df_copy[column].dropna().value_counts())
    grouped.head()

    grouped.reset_index(inplace=True)
    grouped.columns

    grouped.rename(columns={0: 'Key'}, inplace=True)
    grouped.columns

    grouped

    list_ = []
    for row in grouped[column]:
    #    print("%.2f" % (row/df_copy.shape[0]))
        list_.append(row/df_copy.shape[0])
    list_

    grouped[column] = list_
    grouped

    dict_ = grouped.to_dict(orient='split')
    dict_.keys()

    dict_.pop('index')
    dict_.pop('columns')
    dict_

    dict__ = {}

    for line in dict_['data']:
        #print(line[1], ' : ', line[0])
        dict__[line[0]] = line[1]

    dict__

    df_copy[column] = df_copy[column].replace(dict__)
    print(df_copy[column].unique())

ESTRATO
[2.67638699e-01 2.16488303e-01 1.61670043e-01 1.38082992e-01
 8.57654475e-02 3.44486333e-02 2.87793091e-03 5.49181110e-03
 2.52956148e-03 4.96082508e-02 2.09465442e-03 1.10479707e-02
 4.20927905e-03 2.64050715e-03 6.21295801e-04 1.37572642e-03
 9.23068047e-04 1.65752844e-03 7.32241480e-04 1.67084192e-03
 8.83127603e-04 5.03693382e-04 9.16411307e-04 3.55026172e-04
 1.00516785e-03 1.38903990e-03 1.63533931e-03 7.21146912e-04
 4.61534024e-04 3.83872049e-04 1.70856345e-04]
SEXO
[0.46911161 0.53088839]
PARENT
[0.04624882 0.34301297 0.19975326 0.31269152 0.02912324 0.03346122
 0.00423812 0.0139614  0.01125877 0.00625068]
SERSALUD
[0.11928214 0.31451769 0.18559437 0.22948892 0.10803446 0.01001396
 0.01131424 0.00245412 0.01590739 0.00339272]
AFRODES
[0.95985763 0.01837926 0.00717375 0.00899769 0.00559166]
ACTA_NAC
[0.98111039 0.00604654 0.00350145 0.00934163]
DHSERSAL1
[0.2138012  0.35388565 0.22136326 0.11912681 0.05911186 0.01007609
 0.01518403 0.00118046 0.00627065]
PERTE_INDIGENA
[0.09069587 0.86988513 0.00878912 0.02036963 0.01026026]
ENT_PAIS_NAC
[1.37794533e-02 7.91182481e-01 4.06882182e-02 1.62269150e-02
 1.94953747e-02 3.09760335e-03 1.21751788e-02 6.78321880e-03
 4.22924927e-03 1.07417606e-02 5.75586181e-03 5.61385135e-04
 4.75956962e-03 1.02735699e-03 1.12498918e-03 1.95708177e-03
 6.21295801e-05 8.69814122e-04 8.60938467e-04 2.03252484e-03
 2.40064260e-02 1.28253205e-03 1.68193649e-03 1.57720377e-02
 5.76917530e-05 1.14052158e-03 4.07614424e-03 2.32985925e-04
 1.09170548e-03 9.11973480e-04 8.40968245e-04 3.09538444e-03
 3.86090962e-04 1.55323950e-05 2.79583111e-04 3.32837036e-05
 1.57764755e-03 1.28696987e-03 2.66269629e-05 2.68488543e-04
 5.72479702e-04 1.44229382e-04 3.23961382e-04 4.43782715e-06
 1.35353728e-04 7.32241480e-05 1.64199605e-04 3.57245086e-04
 1.66418518e-04 1.08726765e-04 9.98511109e-05 9.09754566e-05
 5.05912295e-04 2.39642666e-04 6.87863208e-05 1.04288938e-04
 3.77215308e-05 2.88458765e-05 3.55026172e-05 7.10052344e-05
 1.73075259e-04 7.76619751e-05 1.10945679e-05 1.57542864e-04
 1.42010469e-04 2.21891358e-05 1.33134815e-05 8.87565430e-06
 6.43484937e-05 2.44080493e-05 6.65674073e-06 2.21891358e-06]
NACIONALIDAD
[0.98980187 0.00732463 0.00287349]
HLENGUA
[0.99452594 0.00547406]
ELENGUA
[0.98756077 0.00781279 0.00462643]
ASISTEN
[0.80702552 0.18726521 0.00570926]
ESCOLARI
[0.44604379 0.11717195 0.06498976 0.13559115 0.12352914 0.08466265
 0.01924686 0.00714934 0.0008099  0.00080547]
NIVACAD
[0.2608222  0.16175214 0.1936224  0.22078412 0.02697977 0.02917206
 0.00991411 0.02099092 0.0128231  0.01924686 0.00445114 0.02415731
 0.00471741 0.00722922 0.00212794 0.00120931]
ALFABET
[0.97681235 0.01405904 0.00912861]
ESCOACUM
[0.19654027 0.12022296 0.01146735 0.03731325 0.17552716 0.10795458
 0.05788258 0.0439833  0.00663233 0.02264623 0.00490824 0.02066696
 0.01628683 0.00881352 0.026678   0.02045616 0.02909883 0.04976801
 0.00706058 0.02421722 0.00021302 0.00692301 0.00217897 0.0010207
 0.00101404 0.00052588]
MUN_RES10
[3.53495122e-02 4.08391044e-02 3.39493777e-04 2.75145283e-04
 1.04288938e-04 5.71969352e-02 7.21146912e-04 2.28548098e-04
 1.24259160e-04 2.50737234e-04 1.12439008e-01 2.33207817e-03
 2.76254740e-03 3.37208296e-02 1.84125448e-02 9.22247049e-02
 8.65376294e-05 1.14052158e-03 7.71294359e-02 6.74549727e-04
 3.83894238e-02 3.47370920e-02 1.80346639e-01 4.57096197e-04
 5.90231011e-04 5.54728394e-05 1.59983669e-03 1.01404350e-03
 3.05744102e-02 2.41861580e-04 2.24110271e-03 4.88160987e-05
 3.52807259e-04 1.17602420e-04 5.80467791e-02 3.15285430e-02
 6.74083755e-02 6.56798418e-04 2.72926370e-04 3.59042406e-02
 2.90677678e-04 3.35055950e-04 2.52956148e-04 1.33134815e-04
 2.21891358e-05 1.77513086e-05 2.37423753e-04 3.10647901e-05
 9.98511109e-05 6.65674073e-06 1.99702222e-05 7.43336048e-04
 6.21295801e-05 1.48667210e-03 2.13015703e-04 1.33134815e-05
 6.65674073e-05 1.10945679e-05 7.76619751e-05 8.87565430e-06
 1.97483308e-04 5.28101431e-04 4.50439456e-04 1.22040247e-04
 1.55323950e-05 2.66269629e-05 3.99404444e-05 4.21593579e-05
 5.10350122e-05 3.21742468e-04 5.76917530e-05 3.04812158e-02
 1.84169827e-04 2.21891358e-06 4.43782715e-06 3.32837036e-05
 3.77215308e-05 5.99106665e-05 4.65971851e-05 2.44080493e-05
 3.55026172e-05 2.88458765e-05 1.42010469e-04 9.54132837e-05]
NOM_MUN_RES10
[6.65674073e-06 3.50765858e-02 4.05706158e-02 2.99553333e-04
 2.52956148e-04 5.54728394e-05 2.81802024e-04 7.21146912e-04
 2.26329185e-04 1.06507852e-04 2.30767012e-04 1.11975255e-01
 6.25733628e-04 2.45633733e-03 3.36542622e-02 1.84125448e-02
 2.39642666e-04 6.65674073e-05 4.43782715e-06 1.13608375e-03
 7.70717441e-02 5.10350122e-05 6.36828196e-04 3.80809948e-02
 9.19074003e-02 5.68929441e-02 3.46971516e-02 1.79612178e-01
 4.54877283e-04 4.10499011e-04 3.99404444e-05 4.65971851e-05
 1.57099081e-03 1.01404350e-03 3.02149462e-02 2.21891358e-06
 6.87863208e-05 6.43484937e-05 2.22557032e-03 1.55323950e-05
 8.43187159e-05 3.14065027e-02 6.05763406e-04 4.72628592e-04
 2.28548098e-04 6.72818974e-02 3.26180296e-04 2.70707456e-04
 7.47773875e-04 3.55935927e-02 2.90677678e-04 8.94222171e-04
 1.10945679e-05 1.70856345e-04 2.21891358e-05 1.22040247e-04
 5.77827284e-02 1.77513086e-05 1.19821333e-04 3.10647901e-05
 9.98511109e-05 1.33134815e-05 8.87565430e-06 1.48667210e-03
 8.20998023e-05 2.66269629e-05 6.72330813e-04 2.15234617e-04
 1.99702222e-05 1.30915901e-04 1.64199605e-04 3.37274863e-04
 4.88160987e-05 2.86239851e-04 4.06061184e-04 1.17602420e-04
 2.44080493e-05 9.31943702e-05 3.55026172e-05 4.21593579e-05
 1.57542864e-04 1.08726765e-04 3.21742468e-04 5.32539258e-05
 3.77215308e-05 6.21295801e-05 3.04057727e-02 1.37572642e-04
 1.48667210e-04 3.32837036e-05 2.88458765e-05 5.76917530e-05
 4.43782715e-05 1.28696987e-04 1.15383506e-04 5.99106665e-05
 8.65376294e-05]
ENT_PAIS_RES10
[1.24924834e-03 9.52362144e-01 1.88873924e-02 1.03179481e-03
 6.94519949e-04 1.10280005e-03 4.06061184e-04 9.29724788e-03
 7.98808887e-05 1.37794533e-03 4.52658369e-04 1.00960568e-03
 3.59463999e-04 1.35353728e-03 2.40752123e-03 5.96887752e-04
 9.54132837e-04 2.32985925e-04 2.30767012e-04 1.61980691e-04
 2.58947214e-03 2.75145283e-04 5.50290567e-04 3.10647901e-04
 2.55175061e-04 4.17155752e-04 3.83872049e-04 3.19523555e-04
 6.43484937e-05 9.98511109e-05 2.61831802e-04 1.57542864e-04
 6.65674073e-05]
SITUA_CONYUGAL
[0.3697065  0.05298988 0.34919043 0.14254079 0.05325171 0.02652711
 0.00579358]
CONACT
[5.28467552e-01 1.77362200e-01 1.57913422e-01 5.42435613e-02
 3.35122517e-02 2.30123527e-02 1.27365639e-02 1.60427452e-03
 1.37794533e-03 2.08799767e-03 4.53545935e-03 1.94820612e-03
 1.00738676e-03 1.90826567e-04]
ACTI_SIN_PAGO1
[8.93188157e-01 1.27587531e-03 1.90826567e-03 3.77215308e-04
 8.18290948e-02 1.09614331e-03 3.15085728e-04 2.88458765e-05
 9.25286961e-04 1.03623264e-03 3.72777481e-04 1.55767733e-03
 1.40235338e-03 1.29140770e-03 5.54728394e-04 7.89933233e-04
 3.50588345e-04 3.63901826e-04 7.78838665e-04 4.01623357e-04
 1.24924834e-03 5.32539258e-05 1.00738676e-03 2.44080493e-05
 1.26921857e-03 9.69665233e-04 2.88458765e-04 2.17453530e-04
 4.72628592e-04 5.76917530e-05 6.98957776e-04 5.10350122e-05
 4.28250320e-04 1.46448296e-04 7.94371060e-04 1.77513086e-05
 8.87565430e-06 2.61831802e-04 1.64199605e-04 4.43782715e-06
 1.10945679e-05 5.01474468e-04 2.21891358e-06 1.55323950e-05
 1.73075259e-04 1.02070024e-04 2.66269629e-05 1.17602420e-04
 1.48667210e-04 9.76321973e-05 1.06507852e-04 7.10052344e-05
 6.65674073e-06 3.99404444e-05 3.10647901e-05 1.33134815e-05
 1.99702222e-05]
ACTI_SIN_PAGO2
[8.95458106e-01 4.23812493e-04 8.22196236e-02 1.37794533e-03
 1.01404350e-03 1.25590508e-03 3.97185530e-04 9.74103060e-04
 1.55323950e-05 1.00516785e-03 4.85942073e-04 7.27803653e-04
 5.45852740e-04 1.18711876e-03 4.21593579e-05 7.61087356e-04
 9.80759800e-04 1.06507852e-04 6.52360591e-04 2.77364197e-04
 1.55323950e-03 3.55026172e-05 1.02735699e-03 4.79285332e-04
 1.12942701e-03 6.43484937e-05 2.92896592e-04 1.53105037e-04
 1.90826567e-04 9.45257183e-04 3.55026172e-04 3.32837036e-05
 2.46299407e-04 4.37125974e-04 8.45406072e-04 6.65674073e-06
 2.21891358e-06 1.13164592e-04 2.44080493e-05 3.99404444e-05
 1.77513086e-05 1.93045481e-04 3.15085728e-04 8.87565430e-06
 1.02070024e-04 1.19821333e-04 9.09754566e-05 4.43782715e-06
 1.33134815e-05 1.66418518e-04 4.65971851e-05 1.10945679e-05
 3.77215308e-05 3.10647901e-05 1.99702222e-05]
ACTI_SIN_PAGO3
[7.84235063e-01 2.66047738e-03 4.59315110e-03 3.20633012e-03
 5.05912295e-03 7.64016322e-02 7.35791742e-03 5.98662883e-03
 6.21517693e-03 7.48439549e-03 5.46296522e-03 4.15158730e-03
 4.74181831e-03 1.29806444e-03 4.76178853e-03 4.54655392e-03
 3.16638967e-03 3.86090962e-03 4.00735792e-03 2.11018681e-03
 2.97112528e-03 4.15380621e-03 3.46372409e-03 1.26699965e-03
 8.58719554e-04 1.55545842e-03 2.26551076e-03 2.44746167e-03
 4.84166942e-03 8.20998023e-05 1.37572642e-04 3.27289752e-03
 1.11833244e-03 4.00292009e-03 3.15085728e-04 2.96003071e-03
 1.75294172e-04 1.26478074e-04 6.06207189e-03 4.50883239e-03
 1.11611353e-03 1.73075259e-04 1.55323950e-04 1.25812400e-03
 2.35204839e-04 4.43782715e-05 1.44229382e-04 1.10945679e-04
 4.48220542e-04 3.50588345e-04 6.21295801e-05 7.72181924e-04
 6.87863208e-05 1.13164592e-04 4.70409678e-04 3.70558567e-04
 1.30915901e-04 6.05763406e-04 8.87565430e-06 1.86388740e-04
 4.10499011e-04 1.28696987e-04 8.65376294e-05 2.21891358e-05
 1.68637432e-04 1.77513086e-05 9.09754566e-05 1.08726765e-04
 9.31943702e-04 1.33134815e-05 1.64199605e-04 1.55323950e-05
 1.79732000e-04 3.55026172e-05 7.10052344e-05 2.88458765e-05
 1.22040247e-04 5.32539258e-05 6.65674073e-05 5.76917530e-05
 5.99106665e-05 5.10350122e-05 3.59463999e-04 1.97483308e-04
 1.17602420e-04 4.43782715e-06 2.44080493e-05 6.65674073e-06
 4.65971851e-05 3.99404444e-05 1.99702222e-05 1.10945679e-05
 7.32241480e-05 3.32837036e-05 2.21891358e-06 3.10647901e-05]
ACTI_SIN_PAGO4
[7.88728363e-01 1.36019402e-03 5.21444690e-04 5.31873584e-03
 3.99848226e-03 7.67522206e-02 6.47035199e-03 5.84683727e-03
 3.94522834e-03 3.72111807e-03 5.34536280e-03 4.41341910e-03
 4.84388834e-03 2.48740212e-03 5.07465535e-03 3.42600256e-03
 4.04507945e-03 3.50144562e-03 8.25879633e-03 3.37718646e-03
 1.10945679e-04 6.32390369e-04 2.18562987e-03 7.86382971e-03
 1.77513086e-05 1.37572642e-04 8.43187159e-05 3.23961382e-03
 1.75959847e-03 2.96003071e-03 1.73075259e-04 4.68634547e-03
 6.21739584e-03 3.68117762e-03 7.58868443e-04 1.18268094e-03
 1.88607654e-03 4.42895150e-03 1.24037269e-03 2.43636711e-03
 6.65674073e-06 4.21593579e-05 7.63306270e-04 1.78400651e-03
 1.70856345e-04 1.48445318e-03 3.86090962e-04 1.59761777e-04
 4.59315110e-04 8.36530418e-04 8.65376294e-05 6.92301036e-04
 1.08726765e-04 1.06507852e-04 4.99255554e-04 6.65674073e-05
 3.55026172e-05 2.13015703e-04 1.53105037e-04 1.88607654e-04
 1.55323950e-05 3.79434221e-04 8.87565430e-06 6.03544493e-04
 4.43782715e-05 1.77513086e-04 1.33134815e-04 1.81950913e-04
 1.61980691e-04 2.66269629e-05 1.35353728e-04 2.88458765e-05
 3.99404444e-05 9.54132837e-05 1.26478074e-04 5.54728394e-05
 7.54430616e-05 1.10945679e-05 5.10350122e-05 9.98511109e-05
 1.97483308e-04 4.43782715e-06 1.75294172e-04 5.99106665e-05
 3.77215308e-05 2.44080493e-05 9.31943702e-05 1.22040247e-04
 3.32837036e-05 5.76917530e-05 3.10647901e-05 1.33134815e-05
 2.21891358e-05 7.10052344e-05 2.21891358e-06 4.65971851e-05]
ACTI_SIN_PAGO5
[8.65098930e-01 2.22335140e-03 8.35487529e-02 2.72482587e-03
 2.74923392e-03 4.14714947e-03 2.16787856e-03 1.06729743e-03
 3.37496755e-03 2.37645644e-03 4.65971851e-05 1.10280005e-03
 1.91270350e-03 2.05471397e-03 2.96224962e-03 5.41414912e-04
 5.85793184e-04 3.32837036e-05 3.38162429e-03 1.99702222e-05
 1.02957590e-03 7.38898221e-04 2.54731278e-03 1.82838479e-03
 1.73740933e-03 1.16049180e-03 2.55175061e-04 1.00738676e-03
 3.81653135e-04 3.77215308e-05 1.06064069e-03 4.43782715e-05
 1.73075259e-04 4.90379900e-04 9.43038270e-04 3.26180296e-04
 6.16857974e-04 6.65674073e-06 3.12866814e-04 7.98808887e-05
 3.10647901e-05 4.43782715e-06 8.87565430e-06 5.36977085e-04
 1.81950913e-04 3.66120740e-04 5.10350122e-05 4.88160987e-05
 2.86239851e-04 1.33134815e-05 6.43484937e-05 1.33134815e-04
 2.21891358e-06 1.26478074e-04 1.10945679e-05 3.55026172e-05
 9.31943702e-05 8.20998023e-05 2.66269629e-05 2.44080493e-05
 1.55323950e-05 3.99404444e-05 5.54728394e-05 1.77513086e-05
 2.88458765e-05]
ACTI_SIN_PAGO6
[3.92488090e-01 2.60500454e-03 3.53517311e-02 1.08540376e-01
 7.45776853e-03 8.62269815e-02 5.72324379e-02 1.60738099e-02
 9.28615331e-03 4.11031551e-02 2.95470532e-02 2.86617067e-02
 1.18489985e-03 2.87504632e-02 1.53326928e-03 1.66640410e-02
 2.96890636e-03 4.59803271e-02 4.07059695e-02 1.30205849e-02
 5.25882517e-04 9.85197628e-04 8.92890823e-03 6.78987554e-04
 3.32837036e-05 3.68783436e-03 1.00738676e-03 2.82245807e-03
 2.08355985e-03 2.04140049e-04 1.73075259e-04 3.55026172e-04
 4.00957683e-03 5.03693382e-04 8.20998023e-05 2.90899570e-03
 4.21593579e-05 2.32985925e-04 3.48369431e-04 1.24259160e-04
 3.30618123e-04 9.09754566e-05 3.61682913e-04 1.21374573e-03
 3.10647901e-05 3.41712691e-04 3.21742468e-04 6.65674073e-05
 1.22040247e-04 3.99404444e-05 8.87565430e-06 4.88160987e-05
 4.65971851e-04 4.50439456e-04 1.10945679e-05 1.81950913e-04
 6.65674073e-06 1.33134815e-05 1.99702222e-05 2.66269629e-05
 2.21891358e-06 2.44080493e-05 2.21891358e-05 1.64199605e-04
 7.98808887e-05 4.43782715e-06 1.77513086e-05 4.43782715e-05]
ACTI_SIN_PAGO7
[6.38159544e-02 3.70225730e-02 7.32241480e-04 3.20573101e-01
 9.51692033e-02 4.51615480e-02 1.57542864e-03 3.93324620e-02
 3.49035105e-03 8.59917767e-02 1.12809566e-02 2.57504920e-02
 3.71046728e-02 5.38641270e-02 2.09066037e-02 2.04140049e-03
 3.88087984e-03 6.72552705e-02 9.44369618e-03 1.37483885e-02
 2.46144083e-02 4.61312132e-03 4.05395510e-03 2.74035827e-03
 1.14052158e-03 8.95331628e-03 1.84169827e-04 4.77066419e-04
 2.01033570e-03 3.68339654e-04 1.08726765e-04 3.77215308e-05
 2.06358963e-04 4.00513900e-03 1.02735699e-03 9.20849134e-04
 1.97483308e-04 1.61980691e-04 2.92896592e-04 4.43782715e-06
 5.83574270e-04 8.20998023e-04 8.20998023e-05 6.72330813e-04
 4.21593579e-04 1.10945679e-05 4.68190764e-04 8.52062813e-04
 8.87565430e-05 1.33134815e-05 1.79732000e-04 8.87565430e-06
 1.99702222e-04 3.72777481e-04 6.87863208e-05 1.99702222e-05
 4.43782715e-05 3.10647901e-05 1.59761777e-04 2.21891358e-05
 4.88160987e-05 6.65674073e-06 7.98808887e-05 2.21891358e-06
 3.32837036e-05]
ACTI_SIN_PAGO8
[1.68763910e-01 7.87714319e-04 1.02598126e-01 3.46217085e-01
 6.66716962e-02 5.08086831e-02 3.60174052e-02 1.01470918e-01
 1.13652753e-02 3.73620668e-02 1.72986502e-02 1.68371162e-02
 2.02853079e-02 7.65525184e-04 4.72850483e-03 4.61534024e-04
 4.02289031e-03 1.09836222e-03 2.47186972e-03 1.10945679e-05
 2.12793812e-03 6.65674073e-05 2.29435664e-03 4.59315110e-04
 1.59761777e-04 9.65227405e-04 5.14787950e-04 7.27803653e-04
 3.37274863e-04 2.04140049e-04 5.76917530e-05 4.43782715e-06
 2.97334419e-04 1.26478074e-04 2.48518320e-04 1.77513086e-05
 6.43484937e-05 8.87565430e-06 1.55323950e-05 8.65376294e-05
 5.32539258e-05 1.13164592e-04 5.10350122e-05 1.33134815e-05
 9.98511109e-05 3.10647901e-05 9.31943702e-05 3.32837036e-05
 1.84169827e-04 2.88458765e-05 2.21891358e-06 3.99404444e-05
 6.65674073e-06 6.21295801e-05]
TAMLOC
[0.93496808 0.02635182 0.01841033 0.02026978]

In [273]:
l_norm = []
for line in df_copy.columns:
    print(line, ' : ', df_copy[line].nunique(), '\n')
    l_norm.append(df_copy[line].nunique())

ENT  :  1

MUN  :  16

NOM_MUN  :  16

ESTRATO  :  31

SEXO  :  2

EDAD  :  96

PARENT  :  10

SERSALUD  :  10

AFRODES  :  5

ACTA_NAC  :  4

DHSERSAL1  :  9

PERTE_INDIGENA  :  5

ENT_PAIS_NAC  :  72

NACIONALIDAD  :  3

HLENGUA  :  2

ELENGUA  :  3

ASISTEN  :  3

ESCOLARI  :  10

NIVACAD  :  16

ALFABET  :  3

ESCOACUM  :  26

MUN_RES10  :  84

NOM_MUN_RES10  :  97

ENT_PAIS_RES10  :  33

SITUA_CONYUGAL  :  7

CONACT  :  14

ACTI_SIN_PAGO1  :  57

ACTI_SIN_PAGO2  :  55

ACTI_SIN_PAGO3  :  96

ACTI_SIN_PAGO4  :  96

ACTI_SIN_PAGO5  :  65

ACTI_SIN_PAGO6  :  68

ACTI_SIN_PAGO7  :  65

ACTI_SIN_PAGO8  :  54

TAMLOC  :  4

In [274]:
l_og[1]

16

In [275]:
len(l_norm)

35

In [276]:
df_copy.shape

(450671, 35)

In [277]:
df_copy.columns[1]

'MUN'

In [279]:
i = 0
l_def = []
for line in range(0, len(l_og)):
    #print(line, ' : ', df_copy[line].nunique(), '\n')
    if(l_og[line] == l_norm[line]):
        l_def.append(df_copy.columns[line])
        print(df_copy.columns[line])
        i = i+1
i

ENT
MUN
NOM_MUN
ESTRATO
SEXO
EDAD
PARENT
SERSALUD
AFRODES
ACTA_NAC
DHSERSAL1
PERTE_INDIGENA
NACIONALIDAD
HLENGUA
ELENGUA
ASISTEN
ESCOLARI
NIVACAD
ALFABET
ESCOACUM
ENT_PAIS_RES10
SITUA_CONYUGAL
CONACT
TAMLOC

24

In [281]:
df_copy = df_copy[l_def]

In [288]:
df_copy.isnull().any().any()

False

In [283]:
file = "../../dataframes/intercensal_persona_clean.csv"

In [284]:
df_copy.to_csv(path_or_buf=file)

In [297]:
numericos = ['EDAD']

In [298]:
categoricos = []

for row in df_copy.columns:
    if row not in numericos:
        if (row != 'ENT') & (row != 'MUN') & (row != 'NOM_MUN') :
#            print(row)
            categoricos.append(row)

In [299]:
f = {}

for column in df_copy.columns:
#    print(column)
    if(column in df_copy[categoricos].columns):
#        print(column, 'categoricos')
        f[column] = lambda x: x.value_counts().index[0]
    elif(column in df_copy[numericos].columns):
#        print(column, 'numericos')
        f[column] = 'mean'
    
f

{'ESTRATO': <function __main__.<lambda>(x)>,
 'SEXO': <function __main__.<lambda>(x)>,
 'EDAD': 'mean',
 'PARENT': <function __main__.<lambda>(x)>,
 'SERSALUD': <function __main__.<lambda>(x)>,
 'AFRODES': <function __main__.<lambda>(x)>,
 'ACTA_NAC': <function __main__.<lambda>(x)>,
 'DHSERSAL1': <function __main__.<lambda>(x)>,
 'PERTE_INDIGENA': <function __main__.<lambda>(x)>,
 'NACIONALIDAD': <function __main__.<lambda>(x)>,
 'HLENGUA': <function __main__.<lambda>(x)>,
 'ELENGUA': <function __main__.<lambda>(x)>,
 'ASISTEN': <function __main__.<lambda>(x)>,
 'ESCOLARI': <function __main__.<lambda>(x)>,
 'NIVACAD': <function __main__.<lambda>(x)>,
 'ALFABET': <function __main__.<lambda>(x)>,
 'ESCOACUM': <function __main__.<lambda>(x)>,
 'ENT_PAIS_RES10': <function __main__.<lambda>(x)>,
 'SITUA_CONYUGAL': <function __main__.<lambda>(x)>,
 'CONACT': <function __main__.<lambda>(x)>,
 'TAMLOC': <function __main__.<lambda>(x)>}

In [301]:
grouped = df_copy.groupby(by=['ENT', 'MUN', 'NOM_MUN']).agg(f)

In [303]:
grouped

                                 ESTRATO      SEXO       EDAD    PARENT  \
ENT MUN NOM_MUN
9   2   Azcapotzalco            0.216488  0.530888  41.857195  0.343013
    3   Coyoacán                0.161670  0.530888  49.039540  0.343013
    4   Cuajimalpa de Morelos   0.267639  0.530888  37.079765  0.343013
    5   Gustavo A. Madero       0.085765  0.530888  41.093112  0.343013
    6   Iztacalco               0.138083  0.530888  42.045709  0.343013
    7   Iztapalapa              0.267639  0.530888  39.340092  0.312692
    8   La Magdalena Contreras  0.216488  0.530888  40.523735  0.343013
    9   Milpa Alta              0.011048  0.530888  35.820166  0.312692
    10  Álvaro Obregón          0.216488  0.530888  40.909885  0.343013
    11  Tláhuac                 0.138083  0.530888  37.168305  0.312692
    12  Tlalpan                 0.085765  0.530888  39.668212  0.343013
    13  Xochimilco              0.138083  0.530888  37.850337  0.312692
    14  Benito Juárez           0.267639  0.530888  43.718880  0.343013
    15  Cuauhtémoc              0.216488  0.530888  42.227342  0.343013
    16  Miguel Hidalgo          0.216488  0.530888  43.157549  0.343013
    17  Venustiano Carranza     0.216488  0.530888  41.194901  0.343013

                                SERSALUD   AFRODES  ACTA_NAC  DHSERSAL1  \
ENT MUN NOM_MUN
9   2   Azcapotzalco            0.314518  0.959858   0.98111   0.353886
    3   Coyoacán                0.314518  0.959858   0.98111   0.353886
    4   Cuajimalpa de Morelos   0.185594  0.959858   0.98111   0.353886
    5   Gustavo A. Madero       0.314518  0.959858   0.98111   0.353886
    6   Iztacalco               0.314518  0.959858   0.98111   0.353886
    7   Iztapalapa              0.314518  0.959858   0.98111   0.353886
    8   La Magdalena Contreras  0.314518  0.959858   0.98111   0.353886
    9   Milpa Alta              0.229489  0.959858   0.98111   0.221363
    10  Álvaro Obregón          0.314518  0.959858   0.98111   0.353886
    11  Tláhuac                 0.229489  0.959858   0.98111   0.221363
    12  Tlalpan                 0.229489  0.959858   0.98111   0.353886
    13  Xochimilco              0.229489  0.959858   0.98111   0.221363
    14  Benito Juárez           0.314518  0.959858   0.98111   0.353886
    15  Cuauhtémoc              0.314518  0.959858   0.98111   0.353886
    16  Miguel Hidalgo          0.185594  0.959858   0.98111   0.353886
    17  Venustiano Carranza     0.314518  0.959858   0.98111   0.353886

                                PERTE_INDIGENA  NACIONALIDAD    ...     \
ENT MUN NOM_MUN                                                 ...
9   2   Azcapotzalco                  0.869885      0.989802    ...
    3   Coyoacán                      0.869885      0.989802    ...
    4   Cuajimalpa de Morelos         0.869885      0.989802    ...
    5   Gustavo A. Madero             0.869885      0.989802    ...
    6   Iztacalco                     0.869885      0.989802    ...
    7   Iztapalapa                    0.869885      0.989802    ...
    8   La Magdalena Contreras        0.869885      0.989802    ...
    9   Milpa Alta                    0.869885      0.989802    ...
    10  Álvaro Obregón                0.869885      0.989802    ...
    11  Tláhuac                       0.869885      0.989802    ...
    12  Tlalpan                       0.869885      0.989802    ...
    13  Xochimilco                    0.869885      0.989802    ...
    14  Benito Juárez                 0.869885      0.989802    ...
    15  Cuauhtémoc                    0.869885      0.989802    ...
    16  Miguel Hidalgo                0.869885      0.989802    ...
    17  Venustiano Carranza           0.869885      0.989802    ...

                                 ELENGUA   ASISTEN  ESCOLARI   NIVACAD  \
ENT MUN NOM_MUN
9   2   Azcapotzalco            0.987561  0.807026  0.446044  0.220784
    3   Coyoacán                0.987561  0.807026  0.446044  0.220784
    4   Cuajimalpa de Morelos   0.987561  0.807026  0.446044  0.260822
    5   Gustavo A. Madero       0.987561  0.807026  0.446044  0.260822
    6   Iztacalco               0.987561  0.807026  0.446044  0.260822
    7   Iztapalapa              0.987561  0.807026  0.446044  0.260822
    8   La Magdalena Contreras  0.987561  0.807026  0.446044  0.260822
    9   Milpa Alta              0.987561  0.807026  0.446044  0.260822
    10  Álvaro Obregón          0.987561  0.807026  0.446044  0.260822
    11  Tláhuac                 0.987561  0.807026  0.446044  0.260822
    12  Tlalpan                 0.987561  0.807026  0.446044  0.260822
    13  Xochimilco              0.987561  0.807026  0.446044  0.260822
    14  Benito Juárez           0.987561  0.807026  0.446044  0.220784
    15  Cuauhtémoc              0.987561  0.807026  0.446044  0.220784
    16  Miguel Hidalgo          0.987561  0.807026  0.446044  0.220784
    17  Venustiano Carranza     0.987561  0.807026  0.446044  0.260822

                                 ALFABET  ESCOACUM  ENT_PAIS_RES10  \
ENT MUN NOM_MUN
9   2   Azcapotzalco            0.976812  0.175527        0.952362
    3   Coyoacán                0.976812  0.175527        0.952362
    4   Cuajimalpa de Morelos   0.976812  0.196540        0.952362
    5   Gustavo A. Madero       0.976812  0.196540        0.952362
    6   Iztacalco               0.976812  0.175527        0.952362
    7   Iztapalapa              0.976812  0.196540        0.952362
    8   La Magdalena Contreras  0.976812  0.196540        0.952362
    9   Milpa Alta              0.976812  0.196540        0.952362
    10  Álvaro Obregón          0.976812  0.196540        0.952362
    11  Tláhuac                 0.976812  0.196540        0.952362
    12  Tlalpan                 0.976812  0.196540        0.952362
    13  Xochimilco              0.976812  0.196540        0.952362
    14  Benito Juárez           0.976812  0.107955        0.952362
    15  Cuauhtémoc              0.976812  0.175527        0.952362
    16  Miguel Hidalgo          0.976812  0.107955        0.952362
    17  Venustiano Carranza     0.976812  0.175527        0.952362

                                SITUA_CONYUGAL    CONACT    TAMLOC
ENT MUN NOM_MUN
9   2   Azcapotzalco                  0.369707  0.528468  0.934968
    3   Coyoacán                      0.369707  0.528468  0.934968
    4   Cuajimalpa de Morelos         0.349190  0.528468  0.934968
    5   Gustavo A. Madero             0.369707  0.528468  0.934968
    6   Iztacalco                     0.369707  0.528468  0.934968
    7   Iztapalapa                    0.369707  0.528468  0.934968
    8   La Magdalena Contreras        0.349190  0.528468  0.934968
    9   Milpa Alta                    0.369707  0.528468  0.020270
    10  Álvaro Obregón                0.369707  0.528468  0.934968
    11  Tláhuac                       0.369707  0.528468  0.934968
    12  Tlalpan                       0.349190  0.528468  0.934968
    13  Xochimilco                    0.369707  0.528468  0.934968
    14  Benito Juárez                 0.369707  0.528468  0.934968
    15  Cuauhtémoc                    0.369707  0.528468  0.934968
    16  Miguel Hidalgo                0.369707  0.528468  0.934968
    17  Venustiano Carranza           0.369707  0.528468  0.934968

[16 rows x 21 columns]

In [304]:
file = "../../dataframes/intercensal_persona_grouped.csv"

In [305]:
grouped.to_csv(path_or_buf=file)