In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(filepath_or_buffer="../../../../Downloads/inegi/inegi/ENH/enh_impute_check.csv")

In [5]:
df.head()

,Unnamed: 0,aire_acond,antiguedad,bano_comp,bano_excus,bano_regad,bomba_agua,calefacc,calentador,chimenea,...,tot_hom,tot_integ,tot_muj,celular,tel_fijo,tv_paga,año,CVE_ENT,CVE_MUN,CVE_LOC
0,0,2,30,2,0,0,1,2,1,2,...,3,4,1,2,1,2,1,1,1,1
1,1,2,30,2,0,0,1,2,1,2,...,2,6,4,1,1,2,1,1,1,1
2,2,2,42,2,0,0,1,2,2,2,...,3,4,1,2,1,2,2,1,1,1
3,3,2,42,2,0,0,1,2,2,2,...,2,6,4,1,1,2,2,1,1,1
4,4,2,26,2,1,0,1,2,1,2,...,3,4,1,2,1,1,1,1,1,1

In [7]:
df[(df.CVE_ENT == 9 )].shape

(8239, 60)

In [8]:
df[(df.CVE_ENT == 9 )].to_csv("C:/Users/aniit/Desktop/w2gis/dataframes/enh_09.csv")